[IV-22-23] Objetivo 2
iscoct/cotan pull request #20
Opened 2022-10-22 16:30 UTC by jmramirezG

## Sobre la estructura del repositorio

* [X] ¿He seguido las mejores prácticas en nombre de las clases y ficheros y
   disposición de los mismos?

## Sobre el análisis del problema

* [ ] ¿Se ha documentado qué análisis se ha hecho sobre el dominio para decir lo
   que se ha creado?
* [ ] ¿Se ha documentado por qué se ha elegido que lo creado sea un objeto valor,
   una entidad o un agregado?
* [ ] ¿He propuesto un producto mínimamente viable, que en muchos casos será un solo
   objeto valor que no dependa de ningún otro (y que sea la base de muchos
   otros)?.

## Sobre la planificación y la programación

* [X] ¿Los issues representan un problema, y no una tarea?
* [X] ¿Todos los mensajes de commit explican el cambio, y no se
      limitan a repetir el nombre del fichero que se ha cambiado?
* [X] ¿Los mensajes de commit siguen el formato estándar y buenas prácticas?
* [ ] ¿Se ha hecho una revisión real del código para comprobar que todos
   los atributos y funciones creadas están respaldadas por una HU?
* [ ] ¿Todos los issues creados están asignados a una HU?
* [ ] ¿Todos los cambios en el código están asignados a un issue al que se
      referencia en un commit? Los issues sobre los que estoy trabajando, ¿han
      sido asignados al primer milestone?
* [ ] ¿Se ha asignado al mismo milestone el PR que se ha hecho?
* [X] ¿Son los milestones sobre los que estoy trabajando productos
   mínimamente viables? ¿O tengo que solicitar al product manager que
   cree milestones adicionales o precise de qué producto se trata?

2022-10-22 16:30 UTC, jmramirezG commented
Cierro issue #18, ya que hemos inicializado el repo con el lenguaje de programación escogido.

2022-10-22 16:32 UTC, jmramirezG commented
Puedes referenciar la milestone correspondiente en el PR? @iscoct

2022-10-23 08:37 UTC, iscoct commented
Está bien por ahora, espero a que se hagan los tipos de datos que se comentaron [aquí](https://github.com/iscoct/cotan/issues/19) para poder proponer el mergeo en el proyecto de JJ, ¿okay?

Todos los cambios necesarios para cumplir el objetivo 2 y el milestone deben de hacerse a la vez para ponerlos allí.

De todas formas es un buen comienzo, ánimo.

2022-10-23 11:13 UTC, jmramirezG commented
Avanza issue #19 porque declaramos estructuras de datos.

Hola @iscoct!

He subido los tipos de dato que se mencionan en el [M1](https://github.com/iscoct/cotan/milestone/4), teniendo en cuenta lo comentado en la issue #19.

Si quieres algún cambio ve comentándome!

2022-10-23 12:39 UTC, iscoct requested changes

2022-10-23 12:39 UTC, iscoct commented on types/models/plato.go
> +	Postre TipoPlato = iota
Creo que sería más fácil implementar la función String de esta manera:

func (s TipoPlato) String() string {
    return []string{"postre", "entrante", "primero", "segundo"}[s]
}

Por defecto iota empieza en 0, así que eso funcionaría.

Otra opción sería hacerlo así:

type TipoPlato string

const (
   Postre TipoPlato = "postre"
   Entrante = "entrante"
   Primero = "primero"
   Segundo = "segundo"
)

Mira a ver si puedes hacerlo de una de las 2 maneras si lo ves más sencillo también.

2022-10-23 12:39 UTC, iscoct commented on types/models/plato.go
> +	Postre TipoPlato = iota
Lo mismo pasaría para EstadoPlato

2022-10-23 12:39 UTC, iscoct commented on iv.yaml
> +entidad: main.go
En entidad debemos de poner las entidades que hemos creado en el proyecto.

Creo que en este caso puede ser entidad el tipo comanda porque gestiona los objetos Plato y Bebida.

[En la documentación del objetivo 2](http://jj.github.io/IV/documentos/proyecto/2.Entidad) viene descrito una entidad como: _clases que van a incluir lógica de negocio, y van a ser capaces de gestionar otras clases, así como almacenamiento y otros _objetos__ por lo que puede creo que puede ser esa.

¿Cómo lo ves?

2022-10-24 10:04 UTC, jmramirezG commented on types/models/plato.go
> +	Postre TipoPlato = iota
He obtado por la segunda opción, si nos remitimos a [este enlace](https://www.sohamkamani.com/golang/enums/#enum-types) podemos ver que definir el tipo nos permite que TipoPlato (o EstadoPlato) dejen de ser comparables con strings, ya que tendrían tipos distintos.

2022-10-24 10:04 UTC, jmramirezG commented on iv.yaml
> +entidad: main.go
He cambiado la entidad a la propuesta

2022-10-24 10:18 UTC, iscoct commented on types/models/plato.go
> +	Postre TipoPlato = iota
Guay!

2022-10-24 10:18 UTC, iscoct commented on iv.yaml
> +entidad: main.go
Perfecto!

2022-10-24 10:19 UTC, iscoct submitted a review, later dismissed

2022-10-25 19:00 UTC, iscoct commented
Esto está listo para revisión @JJ

2022-10-26 05:24 UTC, JJ requested changes
Un proyecto informático resuelve un problema y es un problema específico que está codificado en la historias de usuario. Por favor, desarrollad a partir de las historias de usuario como se ha indicado repetidamente en los objetivos semanales. A @iscoct, deja sólo las historias de usuario que lo sean de verdad (esencialmente, sólo #17). A @jmramirezg, crea issues no con "estructuras propuestas" sin ningúna relación con el problema sino con los problemas que se plantean a partir de la lógica de negocio.
Aparte, yo diría que aparentemente sólo habéis planteado objetos valor. No hay realmente ninguna entidad. En general, no se ha aplicado ningún aspecto del diseño dirigido por dominio.
Finalmente, os aconsejaría que hiciérais esto lo más rápidamente posible, porque es conveniente empezar pronto con el objetivo 3.

2022-10-26 05:24 UTC, JJ commented on README.md
> +  [Intalar y ejecutar](./docs/instalar.md)
A partir de este objetivo, en el README.md tienen que estar sólo las instrucciones para instalar y ejecutar. El resto pueden enlazarse desde el README.md de docs.

2022-10-26 05:24 UTC, JJ commented on main.go
> +package main
Nunca hemos pedido un main. Los productos deben ser mínimos.

2022-10-26 05:24 UTC, JJ commented on types/models/plato.go
> +	Entrante 		 = "entrante"
¿Qué relación tiene con la lógica de negocio?

2022-10-26 05:24 UTC, JJ commented on types/models/mesa.go
> +	Numero int
¿Qué importancia tiene para la lógica de negocio el número de la mesa donde se encargue? ¿De qué forma es un producto mínimo?

2022-10-26 05:24 UTC, JJ commented on types/models/plato.go
> +	EnEspera EstadoPlato = "en espera"
¿Qué relación tiene con la lógica de negocio?

2022-10-27 06:47 UTC, iscoct commented on main.go
> +package main
Ya se ha eliminado con los nuevos cambios

2022-10-27 06:50 UTC, iscoct commented on docs/README.md
> +# Optimizador de Restaurantes
¿Por qué se ha puesto un README.md en docs?

Que yo sepa sólo debería de haber un README.md en el proyecto principal y no más de uno.

A lo mejor tiene sentido varios si una carpeta representa una parte grande del repositorio o proyecto, pero no creo que sea este el caso.

A lo mejor cuando me lo expliques tiene sentido, vamos hablando.

2022-10-27 08:32 UTC, jmramirezG commented on docs/README.md
> +# Optimizador de Restaurantes
Como indicó JJ previamente:

>A partir de este objetivo, en el README.md tienen que estar sólo las instrucciones para instalar y ejecutar. El resto pueden enlazarse desde el README.md de docs.

Entonces he dejado en el README sólo las intrucciones de instalar y ejecutar.

2022-10-27 11:07 UTC, iscoct commented on docs/README.md
> +# Optimizador de Restaurantes
Ah, guay @jmramirezG, no lo había leído bien, gracias por la corrección.

2022-10-27 11:09 UTC, iscoct commented on types/models/plato.go
> +	EnEspera EstadoPlato = "en espera"
En este issue: https://github.com/iscoct/cotan/issues/25 hemos intentado poner información al respecto con la relación de la lógica de negocio.

2022-10-27 11:10 UTC, iscoct commented on types/models/mesa.go
> +	Numero int
En este issue hemos intentado explicar la importancia con la lógica de negocio: https://github.com/iscoct/cotan/issues/24

2022-10-27 11:12 UTC, iscoct commented on types/models/plato.go
> +	Entrante 		 = "entrante"
Aquí hemos intentado explicar la relación con la lógica de negocio: https://github.com/iscoct/cotan/issues/25

2022-10-27 11:12 UTC, iscoct commented on README.md
> +  [Intalar y ejecutar](./docs/instalar.md)
Está resuelto ya

2022-10-27 11:13 UTC, iscoct commented
Está listo para revisar por nuestra parte @JJ

2022-10-27 11:26 UTC, JJ requested changes
Ha mejorado bastante el diseño, pero convendría que realmente mirarais DDD para crear un buen diseño de estructuras de datos, mediante issues que planteen problemas

2022-10-27 11:26 UTC, JJ commented on types/models/plato.go
> +type Plato struct {
¿Esto es un objeto valor o una entidad?

2022-10-27 11:26 UTC, JJ commented on types/models/comanda.go
> +	Platos    []Plato
Las historias de usuario de bebidas y platos son diferentes. Una es #13 y otra es #5 (entiendo) ¿Qué HUs hay en esta historia de usuario? ¿Qué issue ha planteado el problema si las bebidas van en la comanda o no? ¿Cómo usa la comanda la lógica de negocio? ¿#13 y #15 usan lógicas de negocio diferentes?

2022-10-27 12:02 UTC, iscoct commented on types/models/plato.go
> +type Plato struct {
A mi me parece un objeto valor porque aunque platos pueda tener en el futuro pasos, el optimizador de pasos de los platos, no será una lógica del plato en sí, sino de una entidad que optimice los pasos de los platos a hacer.

2022-10-27 12:02 UTC, iscoct commented on types/models/plato.go
> +type Plato struct {
¿Cómo lo ves tú? @JJ

2022-10-27 12:02 UTC, iscoct commented on types/models/comanda.go
> +	Platos    []Plato
Lo dicho [aquí](https://github.com/iscoct/cotan/issues/27) está relacionada con ambas historias porque en una comanda se pide comidas y bebidas.

El problema está definido en [este issue](https://github.com/iscoct/cotan/issues/21) y en [este](https://github.com/iscoct/cotan/issues/15).

 Me parece que son distintas lógicas de negocio en el sentido de que la persona que entrega los platos puede no ser la misma que entrega las bebidas, es una manera de separar responsabilidades aunque una persona pueda hacer ambas al fin y al cabo.

Ya me dice cómo lo ves @JJ

2022-10-27 12:20 UTC, JJ commented on types/models/plato.go
> +type Plato struct {
> A mi me parece un objeto valor porque aunque platos pueda tener en el futuro pasos, el optimizador de pasos de los platos, no será una lógica del plato en sí, sino de una entidad que optimice los pasos de los platos a hacer.

Si pides comidas y bebidas y tienes que optimizar "la comanda", ¿por qué son historias de usuario diferentes?

2022-10-27 13:09 UTC, iscoct commented on types/models/plato.go
> +type Plato struct {
Puedo unirlo en una sola y que sean 2 issues: optimizar el tiempo en sacar los platos y optimizar el tiempo necesario para sacar las bebidas.

Lo distingo porque aunque el fin es optimizar el tiempo, puedo enfocarme en optimizar el tiempo en sacar las bebidas o el tiempo en sacar los platos, o hacer ambos.

Se optimiza el tiempo en sacar las bebidas mejorando la comunicación y la información que se muestra a los empleados del restaurante y los platos haciendo los mismo (mejorando comunicación) y aparte la posibilidad de optimizar los pasos a hacer entre los distintos platos entre todas las comandas.

El optimizador de platos creo que debería ser otra entidad distinta a la de los platos, las bebidas y las comandas, la cual se definiría en un futuro.
En los primeros milestone quiero enfocarme en optimizar la comunicación.

2022-10-30 11:20 UTC, JJ commented on types/models/comanda.go
> +	Platos    []Plato
Yo no tengo que verlo de ninguna forma, es @jmramirezG la persona que tiene que proponer una solución que sirva a la lógica de negocio.

2022-10-30 17:43 UTC, jmramirezG commented
Hola @JJ, con los cambios que acabo de hacer se puede guardar de forma ordenada según el Timestamp las diferentes comandas, que es justo lo que se describe en los requisitos del [M1](https://github.com/iscoct/cotan/milestone/4), en el que se indica que las comandas han de estar ordenadas.

Faltaría algo más para dar soporte a la lógica de negocio propuesta?

2022-10-30 18:24 UTC, jmramirezG commented
Añado también para poder consultar el estado de los platos de una comanda, ajustándonos de nuevo a lo especificado en el M1

2022-11-03 10:57 UTC, iscoct commented on iv.yaml
> +  - types/models/plato.go
Plato no es una entidad creo tal y como está definida:
- 2 platos iguales pueden prepararse y terminarse a la vez.

Ejemplo:
- Macarrones para una mesa, 3 platos, una misma olla, se preparan todos a la vez y después se sacan 3 raciones de un plato mayor hecho.

2022-11-03 10:58 UTC, iscoct commented
go.mod falta y la PR tiene conflictos.

2022-11-03 12:07 UTC, iscoct commented on types/models/instrumento.go
> +type Instrumento struct {
Tal y como has diseñado instrumento y paso, no puedo saber cuándo un instrumento está ocupado o no si no me equivoco.

2022-11-03 12:10 UTC, iscoct commented on types/models/paso.go
> +	Duracion		int
¿Este int que representa exactamente?

2022-11-03 15:11 UTC, jmramirezG commented on types/models/paso.go
> +	Duracion		int
Ese int sería la duración en segundos del paso de elaboración.

2022-11-03 15:13 UTC, jmramirezG commented on types/models/instrumento.go
> +type Instrumento struct {
Se puede inferir cuando un instrumento está en uso de la siguiente manera.

Si un paso está en preparación y requiere un instrumento, ese instrumento está en uso, en caso contrario, ese instrumento no está siendo usado por ese paso.

Para saber si un paso está en preparación, tan solo tenemos que fijarnos en si tiene tiempo de inicio o no.

2022-11-03 15:15 UTC, jmramirezG commented
> go.mod falta y la PR tiene conflictos.

El archivo de go.mod aparece en el PR.

Voy a revisar los conflictos

2022-11-03 15:18 UTC, jmramirezG commented on iv.yaml
> +  - types/models/plato.go
Solucionado!

2022-11-03 15:21 UTC, jmramirezG commented
Los conflictos han sido por la mezcla de código de tu nuevo main con este al mergear el Objetivo 3, como no tengo acceso de escritura al repositorio tienes que resolverlos tu.

Respecto a instrumento, es prácticamente similar.

El iv.yaml ahora también es igual, sólo ha cambiado la representación, yo lo he puesto en la misma línea, tu en la de abajo.

Los README están cambiados de sitio, ya eliges el que quieres conservar en docs y el que quieres conservar como principal.

Muchas gracias por el feedback!

2022-11-03 15:22 UTC, jmramirezG reviewed
En general creo que esto se ajusta mejor a la lógica de negocio de tu problema, si quieres que realice algún otro cambio, no dudes en ponerlo por aquí!

2022-11-03 15:35 UTC, iscoct commented
> Los conflictos han sido por la mezcla de código de tu nuevo main con este al mergear el Objetivo 3, como no tengo acceso de escritura al repositorio tienes que resolverlos tu.
> 
> Respecto a instrumento, es prácticamente similar.
> 
> El iv.yaml ahora también es igual, sólo ha cambiado la representación, yo lo he puesto en la misma línea, tu en la de abajo.
> 
> Los README están cambiados de sitio, ya eliges el que quieres conservar en docs y el que quieres conservar como principal.

No tiene nada que ver que no tengas acceso de escritura, deberías de descargarte los cambios en tu main en el fork y hacer el merge en tu rama del fork para subirlos otra vez.

2022-11-03 15:35 UTC, jmramirezG commented
> > Los conflictos han sido por la mezcla de código de tu nuevo main con este al mergear el Objetivo 3, como no tengo acceso de escritura al repositorio tienes que resolverlos tu.
> > Respecto a instrumento, es prácticamente similar.
> > El iv.yaml ahora también es igual, sólo ha cambiado la representación, yo lo he puesto en la misma línea, tu en la de abajo.
> > Los README están cambiados de sitio, ya eliges el que quieres conservar en docs y el que quieres conservar como principal.
> 
> No tiene nada que ver que no tengas acceso de escritura, deberías de descargarte los cambios en tu main en el fork y hacer el merge en tu rama del fork para subirlos otra vez.

Perfecto! Hago eso entonces.

2022-11-03 15:46 UTC, jmramirezG commented
He intentado hacer un rebase pero ha reventado un poco, por eso salen todos los commits otra vez.

No obstante, ya debería estar!

Espero feedback.

2022-11-03 15:52 UTC, iscoct commented
> He intentado hacer un rebase pero ha reventado un poco, por eso salen todos los commits otra vez.
> 
> No obstante, ya debería estar!
> 
> Espero feedback.

El rebase no hacía falta, ahora hay 50 commits para la PR jajajajaj

2022-11-03 15:53 UTC, iscoct commented on types/models/paso.go
> +	Duracion		int
Okay

2022-11-03 15:53 UTC, iscoct commented on types/models/instrumento.go
> +type Instrumento struct {
Suena bien, sí.

Guay entonces.

2022-11-04 07:52 UTC, jmramirezG commented
Solicitamos revisión @JJ

2022-11-07 13:40 UTC, JJ approved these changes
:+1:

2022-11-07 16:52 UTC, iscoct approved these changes

2022-11-07 16:53 UTC, merged